# Site settings
title: Reading notes
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Some reading notes.
baseurl: "/literature-review" # the subpath of your site, e.g. /blog/
url: "https://stothe2.github.io" # the base hostname & protocol for your site
twitter_username: stothe2
github_username:  stothe2
timezone: America/New_York

# Build settings
markdown: kramdown
